# Utilize a versão 3
version: '3'

# Crie um service com a imagem ghost:1-alpine
services:
  ghost:
      image: ghost:1-alpine
 
# Publique a porta 2368 com bind 2368
      ports:
       - 2368:2368

